name: game_articles_example
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  ln48_core:
    path: ../../ln48_core
  game_articles:
    path: ..

flutter:
  uses-material-design: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
