name: game_map
version: 0.1.0
description: Map game module.
repository: https://github.com/maba3000/ln48
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  game_api:
    path: ../game_api
  intl: ^0.20.2
  ln48_core:
    path: ../ln48_core

flutter:
  generate: true
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
